language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - npm run-script test-travis
  - npm run build
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
